class PhotoFilterPreset {
  const PhotoFilterPreset({
    required this.id,
    required this.label,
    required this.previewMatrix,
    this.brightness = 1,
    this.contrast = 1,
    this.saturation = 1,
    this.gamma = 1,
    this.exposure = 0,
    this.hue = 0,
  });

  final String id;
  final String label;
  final List<double> previewMatrix;

  final double brightness;
  final double contrast;
  final double saturation;
  final double gamma;
  final double exposure;
  final double hue;

  static const List<double> identityMatrix = [
    1,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
  ];

  static const List<PhotoFilterPreset> presets = [
    PhotoFilterPreset(
      id: 'original',
      label: 'Original',
      previewMatrix: identityMatrix,
    ),
    PhotoFilterPreset(
      id: 'vivid',
      label: 'Vivid',
      previewMatrix: [
        1.20,
        -0.05,
        -0.05,
        0,
        4,
        -0.05,
        1.17,
        -0.04,
        0,
        4,
        -0.04,
        -0.04,
        1.20,
        0,
        4,
        0,
        0,
        0,
        1,
        0,
      ],
      contrast: 1.12,
      saturation: 1.28,
      exposure: 0.05,
    ),
    PhotoFilterPreset(
      id: 'warm',
      label: 'Warm',
      previewMatrix: [
        1.10,
        0.03,
        0,
        0,
        7,
        0.02,
        1.03,
        0,
        0,
        2,
        0,
        0,
        0.90,
        0,
        -4,
        0,
        0,
        0,
        1,
        0,
      ],
      brightness: 1.03,
      saturation: 1.08,
      hue: 8,
    ),
    PhotoFilterPreset(
      id: 'cool',
      label: 'Cool',
      previewMatrix: [
        0.92,
        0,
        0.03,
        0,
        -2,
        0,
        1.01,
        0.02,
        0,
        1,
        0.02,
        0.03,
        1.12,
        0,
        7,
        0,
        0,
        0,
        1,
        0,
      ],
      brightness: 1.01,
      saturation: 1.06,
      hue: -9,
    ),
    PhotoFilterPreset(
      id: 'mono',
      label: 'Mono',
      previewMatrix: [
        0.2126,
        0.7152,
        0.0722,
        0,
        0,
        0.2126,
        0.7152,
        0.0722,
        0,
        0,
        0.2126,
        0.7152,
        0.0722,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
      ],
      contrast: 1.08,
      saturation: 0,
    ),
    PhotoFilterPreset(
      id: 'fade',
      label: 'Fade',
      previewMatrix: [
        0.88,
        0.05,
        0.05,
        0,
        18,
        0.05,
        0.88,
        0.05,
        0,
        18,
        0.05,
        0.05,
        0.88,
        0,
        18,
        0,
        0,
        0,
        1,
        0,
      ],
      brightness: 1.08,
      contrast: 0.82,
      saturation: 0.82,
      gamma: 1.06,
    ),
    PhotoFilterPreset(
      id: 'dramatic',
      label: 'Dramatic',
      previewMatrix: [
        1.28,
        -0.12,
        -0.08,
        0,
        -8,
        -0.08,
        1.22,
        -0.08,
        0,
        -8,
        -0.05,
        -0.10,
        1.24,
        0,
        -8,
        0,
        0,
        0,
        1,
        0,
      ],
      contrast: 1.30,
      saturation: 1.10,
      exposure: -0.08,
    ),
    PhotoFilterPreset(
      id: 'vintage',
      label: 'Vintage',
      previewMatrix: [
        0.393,
        0.769,
        0.189,
        0,
        0,
        0.349,
        0.686,
        0.168,
        0,
        0,
        0.272,
        0.534,
        0.131,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
      ],
      brightness: 1.03,
      contrast: 0.94,
      saturation: 0.72,
      hue: 12,
    ),
    PhotoFilterPreset(
      id: 'cinematic',
      label: 'Cinema',
      previewMatrix: [
        0.96,
        0.05,
        0.08,
        0,
        -5,
        -0.03,
        1.02,
        0.06,
        0,
        1,
        -0.08,
        0.06,
        1.12,
        0,
        3,
        0,
        0,
        0,
        1,
        0,
      ],
      contrast: 1.15,
      saturation: 0.92,
      hue: -5,
      exposure: -0.03,
    ),
    PhotoFilterPreset(
      id: 'high_contrast',
      label: 'Punch',
      previewMatrix: [
        1.38,
        -0.18,
        -0.18,
        0,
        -12,
        -0.18,
        1.38,
        -0.18,
        0,
        -12,
        -0.18,
        -0.18,
        1.38,
        0,
        -12,
        0,
        0,
        0,
        1,
        0,
      ],
      contrast: 1.42,
      saturation: 1.12,
    ),
  ];

  static PhotoFilterPreset byId(String id) {
    return presets.firstWhere(
      (preset) => preset.id == id,
      orElse: () => presets.first,
    );
  }
}
